name: Webhook test

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to run in"
                required: true
                default: "qa"
    repository_dispatch:
        types: 
          - trigger-e2e-run
        inputs:
            environment:
                description: "Environment to run in"
                required: false
                default: "qa"

jobs:
    build:
        runs-on: [ubuntu-latest]

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Log
              run: echo "hello world ${{ github.event.inputs.environment }} "
            - name: Log payload
              run: echo "${{ github.event.client_payload }}"